dicionario_alimentos = {
    "abacate_cru": "Abacate Cru",
    "abacaxi_cru": "Abacaxi Cru",
    "abobora_cabotian_cozida": "Abóbora Cabotian Cozida",
    "abobora_moranga_refogada": "Abóbora Moranga Refogada",
    "ameixa_crua": "Ameixa Crua",
    "arroz_integral_cozido": "Arroz Integral Cozido",
    "atum_conserva_em_oleo": "Atum Conserva Em Óleo",
    "aveia_flocos_crua": "Aveia Flocos Crua",
    "bacalhau_salgado_refogado": "Bacalhau Salgado Refogado",
    "banana_da_terra_crua": "Banana Da Terra Crua",
    "banana_maca_crua": "Banana Maca Crua",
    "banana_nanica_crua": "Banana Nanica Crua",
    "banana_ouro_crua": "Banana Ouro Crua",
    "banana_pacova_crua": "Banana Pacova Crua",
    "banana_prata_crua": "Banana Prata Crua",
    "batata_baroa_cozida": "Batata Baroa Cozida",
    "batata_doce_cozida": "Batata Doce Cozida",
    "batata_inglesa_cozida": "Batata Inglesa Cozida",
    "batata_inglesa_saute": "Batata Inglesa Saute",
    "bebida_lactea_pessego": "Bebida Láctea Pêssego",
    "biscoito_salgado_cream_cracker": "Biscoito Salgado Cream Cracker",
    "bolo_pronto_aipim": "Bolo Pronto Aipim",
    "bolo_pronto_chocolate": "Bolo Pronto Chocolate",
    "bolo_pronto_coco": "Bolo Pronto Coco",
    "bolo_pronto_milho": "Bolo Pronto Milho",
    "caju_cru": "Caju Cru",
    "camarao_rio_grande_grande_cozido": "Camarão Rio Grande Grande Cozido",
    "cara_cozido": "Cará Cozido",
    "carambola_crua": "Carambola Crua",
    "carne_bovina_acem_moido_cozido": "Carne Bovina Acém Moído Cozido",
    "carne_bovina_acem_sem_gordura_cozido": "Carne Bovina Acém Sem Gordura Cozido",
    "carne_bovina_bucho_cozido": "Carne Bovina Bucho Cozido",
    "carne_bovina_capa_de_contra_file_sem_gordura_grelhada": "Carne Bovina Capa De Contra Filé Sem Gordura Grelhada",
    "carne_bovina_charque_cozido": "Carne Bovina Charque Cozido",
    "carne_bovina_contra_file_a_milanesa": "Carne Bovina Contra Filé A Milanesa",
    "carne_bovina_contra_file_de_costela_grelhado": "Carne Bovina Contra Filé De Costela Grelhado",
    "carne_bovina_contra_file_sem_gordura_grelhado": "Carne Bovina Contra Filé Sem Gordura Grelhado",
    "carne_bovina_costela_assada": "Carne Bovina Costela Assada",
    "carne_bovina_coxao_duro_sem_gordura_cozido": "Carne Bovina Coxão Duro Sem Gordura Cozido",
    "carne_bovina_coxao_mole_sem_gordura_cozido": "Carne Bovina Coxão Mole Sem Gordura Cozido",
    "carne_bovina_cupim_assado": "Carne Bovina Cupim Assado",
    "carne_bovina_figado_grelhado": "Carne Bovina Fígado Grelhado",
    "carne_bovina_file_mingnon_sem_gordura_grelhado": "Carne Bovina Filé Mingnon Sem Gordura Grelhado",
    "carne_bovina_flanco_sem_gordura_cozido": "Carne Bovina Flanco Sem Gordura Cozido",
    "carne_bovina_lagarto_cozido": "Carne Bovina Lagarto Cozido",
    "carne_bovina_lingua_cozida": "Carne Bovina Língua Cozida",
    "carne_bovina_maminha_grelhada": "Carne Bovina Maminha Grelhada",
    "carne_bovina_miolo_de_alcatra_sem_gordura_grelhado": "Carne Bovina Miolo De Alcatra Sem Gordura Grelhado",
    "carne_bovina_musculo_sem_gordura_cozido": "Carne Bovina Musculo Sem Gordura Cozido",
    "carne_bovina_paleta_sem_gordura_cozida": "Carne Bovina Paleta Sem Gordura Cozida",
    "carne_bovina_patinho_sem_gordura_grelhado": "Carne Bovina Patinho Sem Gordura Grelhado",
    "carne_bovina_peito_sem_gordura_cozido": "Carne Bovina Peito Sem Gordura Cozido",
    "carne_bovina_picanha_sem_gordura_grelhada": "Carne Bovina Picanha Sem Gordura Grelhada",
    "carne_bovina_seca_cozida": "Carne Bovina Seca Cozida",
    "ciriguela_crua": "Ciriguela Crua",
    "ervilha_em_vagem": "Ervilha Em Vagem",
    "ervilha_enlatada_drenada": "Ervilha Enlatada Drenada",
    "feijao_carioca_cozido": "Feijão Carioca Cozido",
    "feijao_carioca_cru": "Feijão Carioca Cru",
    "feijao_fradinho_cozido": "Feijão Fradinho Cozido",
    "feijao_fradinho_cru": "Feijão Fradinho Cru",
    "feijao_preto_cozido": "Feijão Preto Cozido",
    "feijao_preto_cru": "Feijão Preto Cru",
    "feijao_rajado_cozido": "Feijão Rajado Cozido",
    "feijao_rajado_cru": "Feijão Rajado Cru",
    "frango_caipira_inteiro_com_pele_cozido": "Frango Caipira Inteiro Com Pele Cozido",
    "frango_caipira_inteiro_sem_pele_cozido": "Frango Caipira Inteiro Sem Pele Cozido",
    "frango_coracao_grelhado": "Frango Coracao Grelhado",
    "frango_coxa_com_pele_assada": "Frango Coxa Com Pele Assada",
    "frango_coxa_sem_pele_cozida": "Frango Coxa Sem Pele Cozida",
    "frango_file_a_milanesa": "Frango Filé A Milanesa",
    "frango_inteiro_sem_pele_assado": "Frango Inteiro Sem Pele Assado",
    "frango_inteiro_sem_pele_cozido": "Frango Inteiro Sem Pele Cozido",
    "frango_peito_com_pele_assado": "Frango Peito Com Pele Assado",
    "frango_peito_sem_pele_cozido": "Frango Peito Sem Pele Cozido",
    "frango_peito_sem_pele_grelhado": "Frango Peito Sem Pele Grelhado",
    "frango_sobrecoxa_com_pele_assada": "Frango Sobrecoxa Com Pele Assada",
    "frango_sobrecoxa_sem_pele_assada": "Frango Sobrecoxa Sem Pele Assada",
    "goiaba_branca_com_casca_crua": "Goiaba Branca Com Casca Crua",
    "goiaba_vermelha_com_casca_crua": "Goiaba Vermelha Com Casca Crua",
    "graviola_crua": "Graviola Crua",
    "hamburguer_bovino_grelhado": "Hambúrguer Bovino Grelhado",
    "iogurte_natural": "Iogurte Natural",
    "iogurte_natural_desnatado": "Iogurte Natural Desnatado",
    "iogurte_sabor_morango": "Iogurte Sabor Morango",
    "iogurte_sabor_pessego": "Iogurte Sabor Pêssego",
    "jabuticaba_crua": "Jabuticaba Crua",
    "jaca_crua": "Jaca Crua",
    "kiwi_cru": "Kiwi Cru",
    "laranja_baia_crua": "Laranja Baia Crua",
    "laranja_da_terra_crua": "Laranja Da Terra Crua",
    "laranja_lima_crua": "Laranja Lima Crua",
    "laranja_pera_crua": "Laranja Pera Crua",
    "laranja_valencia_crua": "Laranja Valencia Crua",
    "leite_de_cabra": "Leite De Cabra",
    "leite_de_vaca_achocolatado": "Leite De Vaca Achocolatado",
    "leite_de_vaca_desnatado_po": "Leite De Vaca Desnatado Pó",
    "leite_de_vaca_integral_po": "Leite De Vaca Integral Pó",
    "leite_fermentado": "Leite Fermentado",
    "lentilha_cozida": "Lentilha Cozida",
    "maca_argentina_com_casca_crua": "Maçã Argentina Com Casca Crua",
    "maca_fuji_com_casca_crua": "Maçã Fuji Com Casca Crua",
    "macarrao_trigo_cru": "Macarrão Trigo Cru",
    "mamao_formosa_cru": "Mamão Formosa Cru",
    "mamao_papaia_cru": "Mamão Papaia Cru",
    "mandioca_cozida": "Mandioca Cozida",
    "manga_haden_crua": "Manga Haden Crua",
    "manga_palmer_crua": "Manga Palmer Crua",
    "manga_tommy_atkins_crua": "Manga Tommy Atkins Crua",
    "melancia_crua": "Melancia Crua",
    "melao_cru": "Melão Cru",
    "merluza_file_assado": "Merluza File Assado",
    "mexerica_murcote_crua": "Mexerica Murcote Crua",
    "mexerica_rio_crua": "Mexerica Rio Crua",
    "milho_fuba_cru": "Milho Fubá Cru",
    "morango_cru": "Morango Cru",
    "ovo_de_galinha_inteiro_cozido_10minutos": "Ovo De Galinha Inteiro Cozido por 10 Minutos",
    "ovo_de_galinha_inteiro_frito": "Ovo De Galinha Inteiro Frito",
    "pao_aveia_forma": "Pão Aveia Forma",
    "pao_de_soja": "Pão De Soja",
    "pao_gluten_forma": "Pão Gluten Forma",
    "pao_milho_forma": "Pão Milho Forma",
    "pao_trigo_forma_integral": "Pão Trigo Forma Integral",
    "pao_trigo_frances": "Pão Trigo Frances",
    "pao_trigo_sovado": "Pão Trigo Sovado",
    "pera_park_crua": "Pera Park Crua",
    "pera_williams_crua": "Pera Williams Crua",
    "pessego_aurora_cru": "Pêssego Aurora Cru",
    "pinha_crua": "Pinha Crua",
    "queijo_minas_frescal": "Queijo Minas Frescal",
    "queijo_minas_meia_cura": "Queijo Minas Meia Cura",
    "queijo_mozarela": "Queijo Mozarela",
    "queijo_parmesao": "Queijo Parmesão",
    "queijo_pasteurizado": "Queijo Pasteurizado",
    "queijo_prato": "Queijo Prato",
    "queijo_requeijao_cremoso": "Queijo Requeijão Cremoso",
    "queijo_ricota": "Queijo Ricota",
    "salmao_file_com_pele_fresco_grelhado": "Salmão Filé Com Pele Fresco Grelhado",
    "salmao_sem_pele_fresco_grelhado": "Salmão Sem Pele Fresco Grelhado",
    "sardinha_assada": "Sardinha Assada",
    "sardinha_conserva_em_oleo": "Sardinha Conserva Em Óleo",
    "soja_extrato_soluvel_natural_fluido": "Soja Extrato Soluvel Natural Fluído",
    "soja_queijo_tofu": "Soja Queijo Tofu",
    "tangerina_ponca_crua": "Tangerina Ponca Crua",
    "torrada_pao_frances": "Torrada Pão Frances",
    "uva_italia_crua": "Uva Italia Crua",
    "uva_rubi_crua": "Uva Rubi Crua",
}
